import "./globals.css";
import { Inter } from "next/font/google";
import ReactQueryWrapper from "../util/ReactQueryWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crypto",
  description: "Generated by vnesh@",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryWrapper>{children}</ReactQueryWrapper>
      </body>
    </html>
  );
}
