import ReactQueryWrapper from "../../../util/ReactQueryWrapper";

export const metadata = {
  title: "Crypto",
  description: "Generated by vnesh@",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <ReactQueryWrapper>{children}</ReactQueryWrapper>
      </body>
    </html>
  );
}
